"""Security utilities for JWT authentication."""

from datetime import UTC, datetime, timedelta
from typing import Any

import bcrypt
import jwt

from app.core.config import settings


def create_access_token(
    subject: str | Any,
    expires_delta: timedelta | None = None,
    *,
    extra_claims: dict[str, Any] | None = None,
) -> str:
    """Create a JWT access token.

    Args:
        subject: User identifier (UUID string) for the ``sub`` claim.
        expires_delta: Custom expiry. Defaults to ``settings.ACCESS_TOKEN_EXPIRE_MINUTES``.
        extra_claims: Additional claims merged into the payload. Used by the
            service-account flow to set ``svc: true`` and ``svc_name`` so the
            token can be distinguished from a regular user JWT.
    """
    if expires_delta:
        expire = datetime.now(UTC) + expires_delta
    else:
        expire = datetime.now(UTC) + timedelta(minutes=settings.ACCESS_TOKEN_EXPIRE_MINUTES)

    to_encode: dict[str, Any] = {"exp": expire, "sub": str(subject), "type": "access"}
    if extra_claims:
        to_encode.update(extra_claims)
    return jwt.encode(to_encode, settings.SECRET_KEY, algorithm=settings.ALGORITHM)


def create_refresh_token(
    subject: str | Any,
    expires_delta: timedelta | None = None,
    *,
    extra_claims: dict[str, Any] | None = None,
) -> str:
    """Create a JWT refresh token.

    Args:
        subject: User identifier (UUID string) for the ``sub`` claim.
        expires_delta: Custom expiry. Defaults to ``settings.REFRESH_TOKEN_EXPIRE_MINUTES``.
        extra_claims: Additional claims merged into the payload. Same purpose
            as ``create_access_token``'s ``extra_claims``.
    """
    if expires_delta:
        expire = datetime.now(UTC) + expires_delta
    else:
        expire = datetime.now(UTC) + timedelta(minutes=settings.REFRESH_TOKEN_EXPIRE_MINUTES)

    to_encode: dict[str, Any] = {"exp": expire, "sub": str(subject), "type": "refresh"}
    if extra_claims:
        to_encode.update(extra_claims)
    return jwt.encode(to_encode, settings.SECRET_KEY, algorithm=settings.ALGORITHM)


def verify_token(token: str) -> dict[str, Any] | None:
    """Verify a JWT token and return payload."""
    try:
        payload = jwt.decode(
            token,
            settings.SECRET_KEY,
            algorithms=[settings.ALGORITHM],
        )
        return payload
    except jwt.PyJWTError:
        return None


def verify_password(plain_password: str, hashed_password: str) -> bool:
    """Verify a password against a hash."""
    return bcrypt.checkpw(
        plain_password.encode("utf-8"),
        hashed_password.encode("utf-8"),
    )


def get_password_hash(password: str) -> str:
    """Hash a password."""
    return bcrypt.hashpw(
        password.encode("utf-8"),
        bcrypt.gensalt(),
    ).decode("utf-8")


def hash_api_key(plain_api_key: str) -> str:
    """Hash a service API key for storage.

    The plaintext key is generated by the ``create-service-account`` CLI
    command as ``sk_live_`` + 32 hex chars. We never store the plaintext;
    only this bcrypt hash + the first 12 chars of the key (for prefix
    lookup) live in the database.
    """
    return bcrypt.hashpw(
        plain_api_key.encode("utf-8"),
        bcrypt.gensalt(),
    ).decode("utf-8")


def verify_api_key(plain_api_key: str, hashed_api_key: str) -> bool:
    """Verify a service API key against a stored hash."""
    return bcrypt.checkpw(
        plain_api_key.encode("utf-8"),
        hashed_api_key.encode("utf-8"),
    )
